### ISSUE TITLE
Remarks about FutureExportDir.cmake

### ISSUE THREAD

**Issue by Sarcasm** [thejohnfreeman/cmake-future#5]
Hello,

I was wondering why FutureExportDir.cmake is so complex.
I read the implementation, but I'm not sure to understand.

Right now, I often create a variable named:

```cmake
set(FOO_CMAKE_CONFIG_INSTALL_DIR
  ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME})
```

Where `FOO` is the project name uppercased.

I my previous testing, it was portable on all 3 major platforms: Windows, Linux and macOs.
Also, it follows the `GNUInstallDirs` conventions, https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html, where a variable named `CMAKE_INSTALL_XXX` is relative.
And if a full-path version is needed, it should be named `CMAKE_INSTALL_FULL_XXX`.

Reading the implementation, I'm under the impression that `FUTURE_INSTALL_EXPORTDIR` is an absolute path.

If what I use is correct, I guess the only improvement we could expect is for CMake/GNUInstallDirs to export the variable.

What do you think, does `FutureExportDir.cmake` provides anything more apart from the umask-related warning?

**Comment by thejohnfreeman** [comment]
Howdy! Thanks for asking. To be honest, the implementation you've seen is based on my (now old) misunderstanding. I've reimplemented the module and expanded its explanation in the `develop` branch: https://github.com/thejohnfreeman/cmake-future/blob/develop/src/FUTURE_INSTALL_PACKAGEDIR.md

Please check it out and let me know if it still leaves you with questions or seems like the wrong approach. I'm trying to fit into the CMake way of doing things as much as possible.

What I want the module to offer is a variable you can use directly, instead of requiring you to compute your own relative path as you are now. I want to minimize the boilerplate required of users who are following best practices and the most popular conventions. If the module does that, and gets pulled into the official `GNUInstallDirs` eventually, then I'll consider it mission accomplished.

**Comment by Sarcasm** [comment]
Ah, thank you for the answer, I didn't know my method only worked on Windows since CMake 3.7.
Would be very nice to have this upstreamed to CMake.
Having a recent (>= November 2016) CMake version on Windows is less problematic than on Linux I assume, so I may stick with this method in the meantime.

The implementation in the `develop` branch looks good! :+1:

**Comment by Sarcasm** [comment]
Another thought.

By upstreaming this, I think we could go another step further, and really simplify the workflow for users.
Since CMake 3.14, `install(TARGETS ...)` learned to used defaults from `GNUInstallDirs` for the `DESTINATION` arguments.
With your change, `install(TARGETS ...)` could be improved to do the same.
Then, simple CMakeLists.txt should not even need to worry about `GNUInstallDirs` anymore.

**Comment by thejohnfreeman** [comment]
Absolutely! I think CMake is moving in the direction of standardizing and using the most popular conventions as the defaults. I'm writing this set of extensions to implement that vision as a "library solution" in the meantime, but once I've finished field testing them, I'll work on getting them upstreamed into CMake. I think everyone shares the same dream to minimize CMake's boilerplate for the most common use case.

If you take a look at [`future_add_headers`](https://github.com/thejohnfreeman/cmake-future/tree/develop#future_add_headers) and [`future_add_library`](https://github.com/thejohnfreeman/cmake-future/tree/develop#future_add_library), I've bundled the common use case of (1) aliasing the target within the project namespace and (2) installing the target to the standard destinations. I will probably fashion a `future_add_executable` along the same lines. If this behavior got upstreamed, I imagine there would be a `NO_INSTALL` option for people who want to manually specify a custom installation. They lose nothing and everyone else who follows the standard practice gains convenience.
